
version: 2

models:
  - name: employees
    description: "A starter dbt model"
    columns:
      - name: empno
        description: "The primary key for this table"
        tests:
          - unique
          - not_null